variables:
  VERSION_SLUG: ${CI_COMMIT_REF_NAME}+${CI_COMMIT_SHORT_SHA}

stages:
  - scan
  - test
  - quality
  - build
  - publish
  - audit
  - release

include:
  # Scanners
  - component: gitlab.kirauks.net/dev-ops/components/scanners/gitguardian@4.1.5
    inputs:
      job_name: gitguardian
      stage: scan
      allow_failure: true

  - component: gitlab.kirauks.net/dev-ops/components/sonarqube/sonarqube@3.0.0
    inputs:
      job_name: sonarqube
      stage: quality
      allow_failure: true
      needs:
        - job: clippy
          artifacts: true
        - job: test:ui
          artifacts: true
        - job: test:api
          artifacts: true

  - component: gitlab.kirauks.net/dev-ops/components/sbom/grype@1.2.5
    inputs:
      job_name: grype
      stage: quality
      fail_on_severity: critical

  - component: gitlab.kirauks.net/dev-ops/components/rust/clippy@5.1.5
    inputs:
      job_name: clippy
      stage: scan

  # Tests
  - component: gitlab.kirauks.net/dev-ops/components/node/test@5.1.10
    inputs:
      job_name: test:ui
      stage: test
      context: ./ui

  - component: gitlab.kirauks.net/dev-ops/components/rust/test@5.1.5
    inputs:
      job_name: test:api
      stage: test
  - component: gitlab.kirauks.net/dev-ops/components/rust/test@5.1.5
    inputs:
      job_name: test:api:features
      stage: test
      no_default_features: true
      features: $FEATURES

  # Builds
  - component: gitlab.kirauks.net/dev-ops/components/node/build@5.1.10
    inputs:
      job_name: build:ui
      stage: build
      context: ./ui
      artifacts:
        - ./ui/dist/*

  - component: gitlab.kirauks.net/dev-ops/components/rust/build@5.1.5
    inputs:
      job_name: build:api:amd64
      stage: build
      target: x86_64-unknown-linux-gnu
      artifacts:
        - ./target/x86_64-unknown-linux-gnu/release/minecraft-rcon

  - component: gitlab.kirauks.net/dev-ops/components/rust/build@5.1.5
    inputs:
      job_name: build:api:arm64
      stage: build
      target: aarch64-unknown-linux-gnu
      artifacts:
        - ./target/aarch64-unknown-linux-gnu/release/minecraft-rcon

  # Containers
  - component: gitlab.kirauks.net/dev-ops/components/containers/build@5.2.6
    inputs:
      job_name: container:amd64
      stage: publish
      dockerfile: Dockerfile.amd64
      platform: linux/amd64

  - component: gitlab.kirauks.net/dev-ops/components/containers/build@5.2.6
    inputs:
      job_name: container:arm64
      stage: publish
      dockerfile: Dockerfile.arm64
      platform: linux/arm64

  - component: gitlab.kirauks.net/dev-ops/components/containers/manifest@5.2.6
    inputs:
      job_name: manifest
      stage: publish
      platforms: linux/amd64,linux/arm64
      needs:
        - job: container:amd64
          artifacts: false
        - job: container:arm64
          artifacts: false

  - component: gitlab.kirauks.net/dev-ops/components/containers/mirror@5.2.6
    inputs:
      job_name: mirror
      stage: publish
      mirror_manifest: docker://docker.io/${MIRROR_DOCKERHUB_IMAGE}:${CI_COMMIT_REF_NAME////-}
      mirror_credentials: ${MIRROR_DOCKERHUB_USER}:${MIRROR_DOCKERHUB_TOKEN}
      needs:
        - job: manifest
          artifacts: false

  - component: gitlab.kirauks.net/dev-ops/components/containers/audit@5.2.6
    inputs:
      job_name: audit
      stage: audit
      allow_failure: true
      needs:
        - job: manifest
          artifacts: false

  # Release
  - component: gitlab.kirauks.net/dev-ops/components/gitlab/release@2.2.2
    inputs:
      job_name: release
      stage: release

test:ui:
  before_script:
    - npm -v
    - node -v
    - npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_PACKAGE_TOKEN

build:ui:
  before_script:
    - npm -v
    - node -v
    - npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_PACKAGE_TOKEN
    - sed -i -e "s|%VERSION_SLUG%|${VERSION_SLUG}|g" ui/src/environments/environment.prod.ts 

test:api:features:
  parallel:
    matrix:
      - FEATURES: 
        - metrics
        - swagger
        - opentelemetry

container:amd64:
  needs: 
    - job: build:ui
      artifacts: true
    - job: build:api:amd64
      artifacts: true

container:arm64:
  needs: 
    - job: build:ui
      artifacts: true
    - job: build:api:arm64
      artifacts: true
