FROM docker.io/arm64v8/debian:13.2-slim@sha256:025c0ecc472f5a76e30be8a7eee4f3e912945b4a520945cb9ddbd4545c7fd17d

ENV DEBIAN_FRONTEND=noninteractive

# Minecraft RCON Environment
ENV RCON_HOST=localhost
ENV RCON_PORT=25575
ENV RCON_PASSWORD=insecure_secret

# Rocket Environment (https://rocket.rs/guide/v0.5/configuration/#environment-variables)
ENV ROCKET_ADDRESS=0.0.0.0
ENV ROCKET_PORT=8888
ENV ROCKET_LIMITS={json="1 MiB"}
ENV ROCKET_IP_HEADER=X-Forwarded-For

# Rust API
COPY /target/aarch64-unknown-linux-gnu/release /opt
RUN chmod +x /opt/minecraft-rcon

# Angluar UI
COPY /ui/dist/browser /opt/www
ENV ROOT_WWW=/opt/www

# Unprivileged user
RUN useradd \
        --uid 2300 \
        --no-create-home \
        --home-dir /opt \
        --shell /usr/sbin/nologin \
        --user-group \
        minecraft-rcon \
    && chown -R minecraft-rcon:minecraft-rcon /opt

USER minecraft-rcon

WORKDIR /opt
CMD ["./minecraft-rcon"]