FROM debian:12.11-slim@sha256:2424c1850714a4d94666ec928e24d86de958646737b1d113f5b2207be44d37d8

ENV DEBIAN_FRONTEND=noninteractive

# Minecraft RCON Environment
ENV RCON_HOST=localhost
ENV RCON_PORT=25575
ENV RCON_PASSWORD=insecure_secret

# Rocket Environment (https://rocket.rs/guide/v0.5/configuration/#environment-variables)
ENV ROCKET_ADDRESS=0.0.0.0
ENV ROCKET_PORT=8888
ENV ROCKET_LIMITS={json="1 MiB"}
ENV ROCKET_IP_HEADER=X-Forwarded-For

# Rust API
COPY /target/x86_64-unknown-linux-gnu/release /opt
RUN chmod +x /opt/minecraft-rcon

# Angluar UI
COPY /ui/dist/browser /opt/www
ENV ROOT_WWW=/opt/www

# Unprivileged user
RUN adduser \
        --uid 2300 \
        --no-create-home \
        --home /opt \
        --disabled-login \
        --shell /sbin/nologin \
        minecraft-rcon \
    && chown -R minecraft-rcon:minecraft-rcon /opt

USER minecraft-rcon

WORKDIR /opt
CMD ["./minecraft-rcon"]